// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: router/router.proto

package routerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	GatewayAddr   string                 `protobuf:"bytes,3,opt,name=gateway_addr,json=gatewayAddr,proto3" json:"gateway_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRouteRequest) Reset() {
	*x = RegisterRouteRequest{}
	mi := &file_router_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRouteRequest) ProtoMessage() {}

func (x *RegisterRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRouteRequest.ProtoReflect.Descriptor instead.
func (*RegisterRouteRequest) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRouteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterRouteRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RegisterRouteRequest) GetGatewayAddr() string {
	if x != nil {
		return x.GatewayAddr
	}
	return ""
}

type RegisterRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRouteResponse) Reset() {
	*x = RegisterRouteResponse{}
	mi := &file_router_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRouteResponse) ProtoMessage() {}

func (x *RegisterRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRouteResponse.ProtoReflect.Descriptor instead.
func (*RegisterRouteResponse) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterRouteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type KeepAliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveRequest) Reset() {
	*x = KeepAliveRequest{}
	mi := &file_router_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveRequest) ProtoMessage() {}

func (x *KeepAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveRequest.ProtoReflect.Descriptor instead.
func (*KeepAliveRequest) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{2}
}

func (x *KeepAliveRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *KeepAliveRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type KeepAliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAliveResponse) Reset() {
	*x = KeepAliveResponse{}
	mi := &file_router_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAliveResponse) ProtoMessage() {}

func (x *KeepAliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAliveResponse.ProtoReflect.Descriptor instead.
func (*KeepAliveResponse) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{3}
}

func (x *KeepAliveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteRequest) Reset() {
	*x = GetRouteRequest{}
	mi := &file_router_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteRequest) ProtoMessage() {}

func (x *GetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteRequest.ProtoReflect.Descriptor instead.
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{4}
}

func (x *GetRouteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*DeviceRoute         `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteResponse) Reset() {
	*x = GetRouteResponse{}
	mi := &file_router_router_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteResponse) ProtoMessage() {}

func (x *GetRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteResponse.ProtoReflect.Descriptor instead.
func (*GetRouteResponse) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{5}
}

func (x *GetRouteResponse) GetRoutes() []*DeviceRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

type DeviceRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	GatewayAddr   string                 `protobuf:"bytes,2,opt,name=gateway_addr,json=gatewayAddr,proto3" json:"gateway_addr,omitempty"`
	LastActive    int64                  `protobuf:"varint,3,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceRoute) Reset() {
	*x = DeviceRoute{}
	mi := &file_router_router_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceRoute) ProtoMessage() {}

func (x *DeviceRoute) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceRoute.ProtoReflect.Descriptor instead.
func (*DeviceRoute) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceRoute) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceRoute) GetGatewayAddr() string {
	if x != nil {
		return x.GatewayAddr
	}
	return ""
}

func (x *DeviceRoute) GetLastActive() int64 {
	if x != nil {
		return x.LastActive
	}
	return 0
}

type UnregisterRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRouteRequest) Reset() {
	*x = UnregisterRouteRequest{}
	mi := &file_router_router_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRouteRequest) ProtoMessage() {}

func (x *UnregisterRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRouteRequest.ProtoReflect.Descriptor instead.
func (*UnregisterRouteRequest) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterRouteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnregisterRouteRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type UnregisterRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterRouteResponse) Reset() {
	*x = UnregisterRouteResponse{}
	mi := &file_router_router_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterRouteResponse) ProtoMessage() {}

func (x *UnregisterRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterRouteResponse.ProtoReflect.Descriptor instead.
func (*UnregisterRouteResponse) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{8}
}

func (x *UnregisterRouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetOnlineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineStatusRequest) Reset() {
	*x = GetOnlineStatusRequest{}
	mi := &file_router_router_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineStatusRequest) ProtoMessage() {}

func (x *GetOnlineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOnlineStatusRequest) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{9}
}

func (x *GetOnlineStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetOnlineStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	DeviceIds     []string               `protobuf:"bytes,2,rep,name=device_ids,json=deviceIds,proto3" json:"device_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineStatusResponse) Reset() {
	*x = GetOnlineStatusResponse{}
	mi := &file_router_router_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineStatusResponse) ProtoMessage() {}

func (x *GetOnlineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_router_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOnlineStatusResponse) Descriptor() ([]byte, []int) {
	return file_router_router_proto_rawDescGZIP(), []int{10}
}

func (x *GetOnlineStatusResponse) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *GetOnlineStatusResponse) GetDeviceIds() []string {
	if x != nil {
		return x.DeviceIds
	}
	return nil
}

var File_router_router_proto protoreflect.FileDescriptor

const file_router_router_proto_rawDesc = "" +
	"\n" +
	"\x13router/router.proto\x12\x06router\"o\n" +
	"\x14RegisterRouteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12!\n" +
	"\fgateway_addr\x18\x03 \x01(\tR\vgatewayAddr\"K\n" +
	"\x15RegisterRouteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x10KeepAliveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"-\n" +
	"\x11KeepAliveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\x0fGetRouteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"?\n" +
	"\x10GetRouteResponse\x12+\n" +
	"\x06routes\x18\x01 \x03(\v2\x13.router.DeviceRouteR\x06routes\"n\n" +
	"\vDeviceRoute\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12!\n" +
	"\fgateway_addr\x18\x02 \x01(\tR\vgatewayAddr\x12\x1f\n" +
	"\vlast_active\x18\x03 \x01(\x03R\n" +
	"lastActive\"N\n" +
	"\x16UnregisterRouteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"3\n" +
	"\x17UnregisterRouteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"1\n" +
	"\x16GetOnlineStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"P\n" +
	"\x17GetOnlineStatusResponse\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\x12\x1d\n" +
	"\n" +
	"device_ids\x18\x02 \x03(\tR\tdeviceIds2\x86\x03\n" +
	"\rRouterService\x12L\n" +
	"\rRegisterRoute\x12\x1c.router.RegisterRouteRequest\x1a\x1d.router.RegisterRouteResponse\x12@\n" +
	"\tKeepAlive\x12\x18.router.KeepAliveRequest\x1a\x19.router.KeepAliveResponse\x12=\n" +
	"\bGetRoute\x12\x17.router.GetRouteRequest\x1a\x18.router.GetRouteResponse\x12R\n" +
	"\x0fUnregisterRoute\x12\x1e.router.UnregisterRouteRequest\x1a\x1f.router.UnregisterRouteResponse\x12R\n" +
	"\x0fGetOnlineStatus\x12\x1e.router.GetOnlineStatusRequest\x1a\x1f.router.GetOnlineStatusResponseB=Z;github.com/yourusername/im-system/api/proto/router;routerpbb\x06proto3"

var (
	file_router_router_proto_rawDescOnce sync.Once
	file_router_router_proto_rawDescData []byte
)

func file_router_router_proto_rawDescGZIP() []byte {
	file_router_router_proto_rawDescOnce.Do(func() {
		file_router_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_router_proto_rawDesc), len(file_router_router_proto_rawDesc)))
	})
	return file_router_router_proto_rawDescData
}

var file_router_router_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_router_router_proto_goTypes = []any{
	(*RegisterRouteRequest)(nil),    // 0: router.RegisterRouteRequest
	(*RegisterRouteResponse)(nil),   // 1: router.RegisterRouteResponse
	(*KeepAliveRequest)(nil),        // 2: router.KeepAliveRequest
	(*KeepAliveResponse)(nil),       // 3: router.KeepAliveResponse
	(*GetRouteRequest)(nil),         // 4: router.GetRouteRequest
	(*GetRouteResponse)(nil),        // 5: router.GetRouteResponse
	(*DeviceRoute)(nil),             // 6: router.DeviceRoute
	(*UnregisterRouteRequest)(nil),  // 7: router.UnregisterRouteRequest
	(*UnregisterRouteResponse)(nil), // 8: router.UnregisterRouteResponse
	(*GetOnlineStatusRequest)(nil),  // 9: router.GetOnlineStatusRequest
	(*GetOnlineStatusResponse)(nil), // 10: router.GetOnlineStatusResponse
}
var file_router_router_proto_depIdxs = []int32{
	6,  // 0: router.GetRouteResponse.routes:type_name -> router.DeviceRoute
	0,  // 1: router.RouterService.RegisterRoute:input_type -> router.RegisterRouteRequest
	2,  // 2: router.RouterService.KeepAlive:input_type -> router.KeepAliveRequest
	4,  // 3: router.RouterService.GetRoute:input_type -> router.GetRouteRequest
	7,  // 4: router.RouterService.UnregisterRoute:input_type -> router.UnregisterRouteRequest
	9,  // 5: router.RouterService.GetOnlineStatus:input_type -> router.GetOnlineStatusRequest
	1,  // 6: router.RouterService.RegisterRoute:output_type -> router.RegisterRouteResponse
	3,  // 7: router.RouterService.KeepAlive:output_type -> router.KeepAliveResponse
	5,  // 8: router.RouterService.GetRoute:output_type -> router.GetRouteResponse
	8,  // 9: router.RouterService.UnregisterRoute:output_type -> router.UnregisterRouteResponse
	10, // 10: router.RouterService.GetOnlineStatus:output_type -> router.GetOnlineStatusResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_router_router_proto_init() }
func file_router_router_proto_init() {
	if File_router_router_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_router_proto_rawDesc), len(file_router_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_router_router_proto_goTypes,
		DependencyIndexes: file_router_router_proto_depIdxs,
		MessageInfos:      file_router_router_proto_msgTypes,
	}.Build()
	File_router_router_proto = out.File
	file_router_router_proto_goTypes = nil
	file_router_router_proto_depIdxs = nil
}
