// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: gateway/gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_PING         MessageType = 0
	MessageType_PONG         MessageType = 1
	MessageType_AUTH         MessageType = 2
	MessageType_CHAT         MessageType = 3
	MessageType_NOTIFICATION MessageType = 4
	MessageType_ACK          MessageType = 5
	MessageType_ERROR        MessageType = 6
	MessageType_TYPING       MessageType = 7
	MessageType_READ_RECEIPT MessageType = 8
	MessageType_PRESENCE     MessageType = 9
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "PING",
		1: "PONG",
		2: "AUTH",
		3: "CHAT",
		4: "NOTIFICATION",
		5: "ACK",
		6: "ERROR",
		7: "TYPING",
		8: "READ_RECEIPT",
		9: "PRESENCE",
	}
	MessageType_value = map[string]int32{
		"PING":         0,
		"PONG":         1,
		"AUTH":         2,
		"CHAT":         3,
		"NOTIFICATION": 4,
		"ACK":          5,
		"ERROR":        6,
		"TYPING":       7,
		"READ_RECEIPT": 8,
		"PRESENCE":     9,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_gateway_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_gateway_gateway_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

type GatewayMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=gateway.MessageType" json:"type,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	MsgId         *string                `protobuf:"bytes,4,opt,name=msg_id,json=msgId,proto3,oneof" json:"msg_id,omitempty"`
	ErrorCode     *int32                 `protobuf:"varint,5,opt,name=error_code,json=errorCode,proto3,oneof" json:"error_code,omitempty"`
	ErrorMsg      *string                `protobuf:"bytes,6,opt,name=error_msg,json=errorMsg,proto3,oneof" json:"error_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayMessage) Reset() {
	*x = GatewayMessage{}
	mi := &file_gateway_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMessage) ProtoMessage() {}

func (x *GatewayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMessage.ProtoReflect.Descriptor instead.
func (*GatewayMessage) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_PING
}

func (x *GatewayMessage) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GatewayMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GatewayMessage) GetMsgId() string {
	if x != nil && x.MsgId != nil {
		return *x.MsgId
	}
	return ""
}

func (x *GatewayMessage) GetErrorCode() int32 {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return 0
}

func (x *GatewayMessage) GetErrorMsg() string {
	if x != nil && x.ErrorMsg != nil {
		return *x.ErrorMsg
	}
	return ""
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	ConvType      string                 `protobuf:"bytes,2,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`
	Body          *structpb.Struct       `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ReplyTo       *string                `protobuf:"bytes,4,opt,name=reply_to,json=replyTo,proto3,oneof" json:"reply_to,omitempty"`
	Mentions      []int64                `protobuf:"varint,5,rep,packed,name=mentions,proto3" json:"mentions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *SendRequest) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *SendRequest) GetConvType() string {
	if x != nil {
		return x.ConvType
	}
	return ""
}

func (x *SendRequest) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SendRequest) GetReplyTo() string {
	if x != nil && x.ReplyTo != nil {
		return *x.ReplyTo
	}
	return ""
}

func (x *SendRequest) GetMentions() []int64 {
	if x != nil {
		return x.Mentions
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *SendResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*ConvSync            `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_gateway_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *SyncRequest) GetConversations() []*ConvSync {
	if x != nil {
		return x.Conversations
	}
	return nil
}

type ConvSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	SinceSeq      int64                  `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvSync) Reset() {
	*x = ConvSync{}
	mi := &file_gateway_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvSync) ProtoMessage() {}

func (x *ConvSync) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvSync.ProtoReflect.Descriptor instead.
func (*ConvSync) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ConvSync) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *ConvSync) GetSinceSeq() int64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvMessages  []*ConvMessages        `protobuf:"bytes,1,rep,name=conv_messages,json=convMessages,proto3" json:"conv_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_gateway_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *SyncResponse) GetConvMessages() []*ConvMessages {
	if x != nil {
		return x.ConvMessages
	}
	return nil
}

type ConvMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Messages      []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvMessages) Reset() {
	*x = ConvMessages{}
	mi := &file_gateway_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvMessages) ProtoMessage() {}

func (x *ConvMessages) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvMessages.ProtoReflect.Descriptor instead.
func (*ConvMessages) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ConvMessages) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *ConvMessages) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ConvMessages) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ConvId        int64                  `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	SenderId      int64                  `protobuf:"varint,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ConvType      string                 `protobuf:"bytes,5,opt,name=conv_type,json=convType,proto3" json:"conv_type,omitempty"`
	Body          *structpb.Struct       `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	ReplyTo       *string                `protobuf:"bytes,7,opt,name=reply_to,json=replyTo,proto3,oneof" json:"reply_to,omitempty"`
	Mentions      []int64                `protobuf:"varint,8,rep,packed,name=mentions,proto3" json:"mentions,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_gateway_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_gateway_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ChatMessage) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *ChatMessage) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *ChatMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *ChatMessage) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessage) GetConvType() string {
	if x != nil {
		return x.ConvType
	}
	return ""
}

func (x *ChatMessage) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ChatMessage) GetReplyTo() string {
	if x != nil && x.ReplyTo != nil {
		return *x.ReplyTo
	}
	return ""
}

func (x *ChatMessage) GetMentions() []int64 {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *ChatMessage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_gateway_gateway_proto protoreflect.FileDescriptor

const file_gateway_gateway_proto_rawDesc = "" +
	"\n" +
	"\x15gateway/gateway.proto\x12\agateway\x1a\x1cgoogle/protobuf/struct.proto\"\x95\x02\n" +
	"\x0eGatewayMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.gateway.MessageTypeR\x04type\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\x06msg_id\x18\x04 \x01(\tH\x00R\x05msgId\x88\x01\x01\x12\"\n" +
	"\n" +
	"error_code\x18\x05 \x01(\x05H\x01R\terrorCode\x88\x01\x01\x12 \n" +
	"\terror_msg\x18\x06 \x01(\tH\x02R\berrorMsg\x88\x01\x01B\t\n" +
	"\a_msg_idB\r\n" +
	"\v_error_codeB\f\n" +
	"\n" +
	"_error_msg\"\xb9\x01\n" +
	"\vSendRequest\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x1b\n" +
	"\tconv_type\x18\x02 \x01(\tR\bconvType\x12+\n" +
	"\x04body\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04body\x12\x1e\n" +
	"\breply_to\x18\x04 \x01(\tH\x00R\areplyTo\x88\x01\x01\x12\x1a\n" +
	"\bmentions\x18\x05 \x03(\x03R\bmentionsB\v\n" +
	"\t_reply_to\"V\n" +
	"\fSendResponse\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"F\n" +
	"\vSyncRequest\x127\n" +
	"\rconversations\x18\x01 \x03(\v2\x11.gateway.ConvSyncR\rconversations\"@\n" +
	"\bConvSync\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x03R\bsinceSeq\"J\n" +
	"\fSyncResponse\x12:\n" +
	"\rconv_messages\x18\x01 \x03(\v2\x15.gateway.ConvMessagesR\fconvMessages\"t\n" +
	"\fConvMessages\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x120\n" +
	"\bmessages\x18\x02 \x03(\v2\x14.gateway.ChatMessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\x9e\x02\n" +
	"\vChatMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x17\n" +
	"\aconv_id\x18\x02 \x01(\x03R\x06convId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\x03R\bsenderId\x12\x1b\n" +
	"\tconv_type\x18\x05 \x01(\tR\bconvType\x12+\n" +
	"\x04body\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04body\x12\x1e\n" +
	"\breply_to\x18\a \x01(\tH\x00R\areplyTo\x88\x01\x01\x12\x1a\n" +
	"\bmentions\x18\b \x03(\x03R\bmentions\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAtB\v\n" +
	"\t_reply_to*\x87\x01\n" +
	"\vMessageType\x12\b\n" +
	"\x04PING\x10\x00\x12\b\n" +
	"\x04PONG\x10\x01\x12\b\n" +
	"\x04AUTH\x10\x02\x12\b\n" +
	"\x04CHAT\x10\x03\x12\x10\n" +
	"\fNOTIFICATION\x10\x04\x12\a\n" +
	"\x03ACK\x10\x05\x12\t\n" +
	"\x05ERROR\x10\x06\x12\n" +
	"\n" +
	"\x06TYPING\x10\a\x12\x10\n" +
	"\fREAD_RECEIPT\x10\b\x12\f\n" +
	"\bPRESENCE\x10\t2\xbb\x01\n" +
	"\x0eGatewayService\x12?\n" +
	"\aConnect\x12\x17.gateway.GatewayMessage\x1a\x17.gateway.GatewayMessage(\x010\x01\x123\n" +
	"\x04Send\x12\x14.gateway.SendRequest\x1a\x15.gateway.SendResponse\x123\n" +
	"\x04Sync\x12\x14.gateway.SyncRequest\x1a\x15.gateway.SyncResponseB@Z>github.com/dollarkillerx/im-system/api/proto/gateway;gatewaypbb\x06proto3"

var (
	file_gateway_gateway_proto_rawDescOnce sync.Once
	file_gateway_gateway_proto_rawDescData []byte
)

func file_gateway_gateway_proto_rawDescGZIP() []byte {
	file_gateway_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_gateway_proto_rawDesc), len(file_gateway_gateway_proto_rawDesc)))
	})
	return file_gateway_gateway_proto_rawDescData
}

var file_gateway_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gateway_gateway_proto_goTypes = []any{
	(MessageType)(0),        // 0: gateway.MessageType
	(*GatewayMessage)(nil),  // 1: gateway.GatewayMessage
	(*SendRequest)(nil),     // 2: gateway.SendRequest
	(*SendResponse)(nil),    // 3: gateway.SendResponse
	(*SyncRequest)(nil),     // 4: gateway.SyncRequest
	(*ConvSync)(nil),        // 5: gateway.ConvSync
	(*SyncResponse)(nil),    // 6: gateway.SyncResponse
	(*ConvMessages)(nil),    // 7: gateway.ConvMessages
	(*ChatMessage)(nil),     // 8: gateway.ChatMessage
	(*structpb.Struct)(nil), // 9: google.protobuf.Struct
}
var file_gateway_gateway_proto_depIdxs = []int32{
	0,  // 0: gateway.GatewayMessage.type:type_name -> gateway.MessageType
	9,  // 1: gateway.GatewayMessage.payload:type_name -> google.protobuf.Struct
	9,  // 2: gateway.SendRequest.body:type_name -> google.protobuf.Struct
	5,  // 3: gateway.SyncRequest.conversations:type_name -> gateway.ConvSync
	7,  // 4: gateway.SyncResponse.conv_messages:type_name -> gateway.ConvMessages
	8,  // 5: gateway.ConvMessages.messages:type_name -> gateway.ChatMessage
	9,  // 6: gateway.ChatMessage.body:type_name -> google.protobuf.Struct
	1,  // 7: gateway.GatewayService.Connect:input_type -> gateway.GatewayMessage
	2,  // 8: gateway.GatewayService.Send:input_type -> gateway.SendRequest
	4,  // 9: gateway.GatewayService.Sync:input_type -> gateway.SyncRequest
	1,  // 10: gateway.GatewayService.Connect:output_type -> gateway.GatewayMessage
	3,  // 11: gateway.GatewayService.Send:output_type -> gateway.SendResponse
	6,  // 12: gateway.GatewayService.Sync:output_type -> gateway.SyncResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_gateway_gateway_proto_init() }
func file_gateway_gateway_proto_init() {
	if File_gateway_gateway_proto != nil {
		return
	}
	file_gateway_gateway_proto_msgTypes[0].OneofWrappers = []any{}
	file_gateway_gateway_proto_msgTypes[1].OneofWrappers = []any{}
	file_gateway_gateway_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_gateway_proto_rawDesc), len(file_gateway_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_gateway_proto_depIdxs,
		EnumInfos:         file_gateway_gateway_proto_enumTypes,
		MessageInfos:      file_gateway_gateway_proto_msgTypes,
	}.Build()
	File_gateway_gateway_proto = out.File
	file_gateway_gateway_proto_goTypes = nil
	file_gateway_gateway_proto_depIdxs = nil
}
