// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: message/message.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConversationType int32

const (
	ConversationType_DIRECT  ConversationType = 0
	ConversationType_GROUP   ConversationType = 1
	ConversationType_CHANNEL ConversationType = 2
)

// Enum value maps for ConversationType.
var (
	ConversationType_name = map[int32]string{
		0: "DIRECT",
		1: "GROUP",
		2: "CHANNEL",
	}
	ConversationType_value = map[string]int32{
		"DIRECT":  0,
		"GROUP":   1,
		"CHANNEL": 2,
	}
)

func (x ConversationType) Enum() *ConversationType {
	p := new(ConversationType)
	*p = x
	return p
}

func (x ConversationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[0].Descriptor()
}

func (ConversationType) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[0]
}

func (x ConversationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationType.Descriptor instead.
func (ConversationType) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{0}
}

type ConversationRole int32

const (
	ConversationRole_OWNER     ConversationRole = 0
	ConversationRole_ADMIN     ConversationRole = 1
	ConversationRole_PUBLISHER ConversationRole = 2
	ConversationRole_MEMBER    ConversationRole = 3
	ConversationRole_VIEWER    ConversationRole = 4
)

// Enum value maps for ConversationRole.
var (
	ConversationRole_name = map[int32]string{
		0: "OWNER",
		1: "ADMIN",
		2: "PUBLISHER",
		3: "MEMBER",
		4: "VIEWER",
	}
	ConversationRole_value = map[string]int32{
		"OWNER":     0,
		"ADMIN":     1,
		"PUBLISHER": 2,
		"MEMBER":    3,
		"VIEWER":    4,
	}
)

func (x ConversationRole) Enum() *ConversationRole {
	p := new(ConversationRole)
	*p = x
	return p
}

func (x ConversationRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationRole) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[1].Descriptor()
}

func (ConversationRole) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[1]
}

func (x ConversationRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationRole.Descriptor instead.
func (ConversationRole) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{1}
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ConvType      ConversationType       `protobuf:"varint,3,opt,name=conv_type,json=convType,proto3,enum=message.ConversationType" json:"conv_type,omitempty"`
	Body          *structpb.Struct       `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ReplyTo       *string                `protobuf:"bytes,5,opt,name=reply_to,json=replyTo,proto3,oneof" json:"reply_to,omitempty"`
	Mentions      []int64                `protobuf:"varint,6,rep,packed,name=mentions,proto3" json:"mentions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *SendMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageRequest) GetConvType() ConversationType {
	if x != nil {
		return x.ConvType
	}
	return ConversationType_DIRECT
}

func (x *SendMessageRequest) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SendMessageRequest) GetReplyTo() string {
	if x != nil && x.ReplyTo != nil {
		return *x.ReplyTo
	}
	return ""
}

func (x *SendMessageRequest) GetMentions() []int64 {
	if x != nil {
		return x.Mentions
	}
	return nil
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Seq           int64                  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_message_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageResponse) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *SendMessageResponse) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SendMessageResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type PullMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	SinceSeq      int64                  `protobuf:"varint,2,opt,name=since_seq,json=sinceSeq,proto3" json:"since_seq,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesRequest) Reset() {
	*x = PullMessagesRequest{}
	mi := &file_message_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesRequest) ProtoMessage() {}

func (x *PullMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesRequest.ProtoReflect.Descriptor instead.
func (*PullMessagesRequest) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{2}
}

func (x *PullMessagesRequest) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *PullMessagesRequest) GetSinceSeq() int64 {
	if x != nil {
		return x.SinceSeq
	}
	return 0
}

func (x *PullMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PullMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesResponse) Reset() {
	*x = PullMessagesResponse{}
	mi := &file_message_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesResponse) ProtoMessage() {}

func (x *PullMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesResponse.ProtoReflect.Descriptor instead.
func (*PullMessagesResponse) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{3}
}

func (x *PullMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *PullMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	ConvId        int64                  `protobuf:"varint,2,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	SenderId      int64                  `protobuf:"varint,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ConvType      ConversationType       `protobuf:"varint,5,opt,name=conv_type,json=convType,proto3,enum=message.ConversationType" json:"conv_type,omitempty"`
	Body          *structpb.Struct       `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	ReplyTo       *string                `protobuf:"bytes,7,opt,name=reply_to,json=replyTo,proto3,oneof" json:"reply_to,omitempty"`
	Mentions      []int64                `protobuf:"varint,8,rep,packed,name=mentions,proto3" json:"mentions,omitempty"`
	Visibility    string                 `protobuf:"bytes,9,opt,name=visibility,proto3" json:"visibility,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *Message) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *Message) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Message) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetConvType() ConversationType {
	if x != nil {
		return x.ConvType
	}
	return ConversationType_DIRECT
}

func (x *Message) GetBody() *structpb.Struct {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Message) GetReplyTo() string {
	if x != nil && x.ReplyTo != nil {
		return *x.ReplyTo
	}
	return ""
}

func (x *Message) GetMentions() []int64 {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *Message) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Message) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_message_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetConversationRequest) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

type GetConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationResponse) Reset() {
	*x = GetConversationResponse{}
	mi := &file_message_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationResponse) ProtoMessage() {}

func (x *GetConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationResponse.ProtoReflect.Descriptor instead.
func (*GetConversationResponse) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{6}
}

func (x *GetConversationResponse) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          ConversationType       `protobuf:"varint,2,opt,name=type,proto3,enum=message.ConversationType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	OwnerId       int64                  `protobuf:"varint,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Members       []*ConversationMember  `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_message_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{7}
}

func (x *Conversation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Conversation) GetType() ConversationType {
	if x != nil {
		return x.Type
	}
	return ConversationType_DIRECT
}

func (x *Conversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Conversation) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Conversation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Conversation) GetMembers() []*ConversationMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type ConversationMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          ConversationRole       `protobuf:"varint,2,opt,name=role,proto3,enum=message.ConversationRole" json:"role,omitempty"`
	Muted         bool                   `protobuf:"varint,3,opt,name=muted,proto3" json:"muted,omitempty"`
	LastReadSeq   int64                  `protobuf:"varint,4,opt,name=last_read_seq,json=lastReadSeq,proto3" json:"last_read_seq,omitempty"`
	JoinedAt      int64                  `protobuf:"varint,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationMember) Reset() {
	*x = ConversationMember{}
	mi := &file_message_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMember) ProtoMessage() {}

func (x *ConversationMember) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMember.ProtoReflect.Descriptor instead.
func (*ConversationMember) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{8}
}

func (x *ConversationMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConversationMember) GetRole() ConversationRole {
	if x != nil {
		return x.Role
	}
	return ConversationRole_OWNER
}

func (x *ConversationMember) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *ConversationMember) GetLastReadSeq() int64 {
	if x != nil {
		return x.LastReadSeq
	}
	return 0
}

func (x *ConversationMember) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

type CreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ConversationType       `protobuf:"varint,1,opt,name=type,proto3,enum=message.ConversationType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	MemberIds     []int64                `protobuf:"varint,4,rep,packed,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_message_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{9}
}

func (x *CreateConversationRequest) GetType() ConversationType {
	if x != nil {
		return x.Type
	}
	return ConversationType_DIRECT
}

func (x *CreateConversationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateConversationRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateConversationRequest) GetMemberIds() []int64 {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

type CreateConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationResponse) Reset() {
	*x = CreateConversationResponse{}
	mi := &file_message_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationResponse) ProtoMessage() {}

func (x *CreateConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationResponse.ProtoReflect.Descriptor instead.
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{10}
}

func (x *CreateConversationResponse) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *CreateConversationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateReadSeqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReadSeqRequest) Reset() {
	*x = UpdateReadSeqRequest{}
	mi := &file_message_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReadSeqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReadSeqRequest) ProtoMessage() {}

func (x *UpdateReadSeqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReadSeqRequest.ProtoReflect.Descriptor instead.
func (*UpdateReadSeqRequest) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateReadSeqRequest) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *UpdateReadSeqRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateReadSeqRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type UpdateReadSeqResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateReadSeqResponse) Reset() {
	*x = UpdateReadSeqResponse{}
	mi := &file_message_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateReadSeqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReadSeqResponse) ProtoMessage() {}

func (x *UpdateReadSeqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReadSeqResponse.ProtoReflect.Descriptor instead.
func (*UpdateReadSeqResponse) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateReadSeqResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type NotifyNewMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	MsgId         string                 `protobuf:"bytes,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	SenderId      int64                  `protobuf:"varint,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	RecipientIds  []int64                `protobuf:"varint,5,rep,packed,name=recipient_ids,json=recipientIds,proto3" json:"recipient_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNewMessageRequest) Reset() {
	*x = NotifyNewMessageRequest{}
	mi := &file_message_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNewMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewMessageRequest) ProtoMessage() {}

func (x *NotifyNewMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewMessageRequest.ProtoReflect.Descriptor instead.
func (*NotifyNewMessageRequest) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{13}
}

func (x *NotifyNewMessageRequest) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *NotifyNewMessageRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *NotifyNewMessageRequest) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *NotifyNewMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *NotifyNewMessageRequest) GetRecipientIds() []int64 {
	if x != nil {
		return x.RecipientIds
	}
	return nil
}

type NotifyNewMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotifiedCount int32                  `protobuf:"varint,2,opt,name=notified_count,json=notifiedCount,proto3" json:"notified_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNewMessageResponse) Reset() {
	*x = NotifyNewMessageResponse{}
	mi := &file_message_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNewMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNewMessageResponse) ProtoMessage() {}

func (x *NotifyNewMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNewMessageResponse.ProtoReflect.Descriptor instead.
func (*NotifyNewMessageResponse) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{14}
}

func (x *NotifyNewMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NotifyNewMessageResponse) GetNotifiedCount() int32 {
	if x != nil {
		return x.NotifiedCount
	}
	return 0
}

var File_message_message_proto protoreflect.FileDescriptor

const file_message_message_proto_rawDesc = "" +
	"\n" +
	"\x15message/message.proto\x12\amessage\x1a\x1cgoogle/protobuf/struct.proto\"\xf8\x01\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x126\n" +
	"\tconv_type\x18\x03 \x01(\x0e2\x19.message.ConversationTypeR\bconvType\x12+\n" +
	"\x04body\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04body\x12\x1e\n" +
	"\breply_to\x18\x05 \x01(\tH\x00R\areplyTo\x88\x01\x01\x12\x1a\n" +
	"\bmentions\x18\x06 \x03(\x03R\bmentionsB\v\n" +
	"\t_reply_to\"]\n" +
	"\x13SendMessageResponse\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x03R\x03seq\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"a\n" +
	"\x13PullMessagesRequest\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x1b\n" +
	"\tsince_seq\x18\x02 \x01(\x03R\bsinceSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"_\n" +
	"\x14PullMessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.message.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xd5\x02\n" +
	"\aMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x17\n" +
	"\aconv_id\x18\x02 \x01(\x03R\x06convId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\x03R\bsenderId\x126\n" +
	"\tconv_type\x18\x05 \x01(\x0e2\x19.message.ConversationTypeR\bconvType\x12+\n" +
	"\x04body\x18\x06 \x01(\v2\x17.google.protobuf.StructR\x04body\x12\x1e\n" +
	"\breply_to\x18\a \x01(\tH\x00R\areplyTo\x88\x01\x01\x12\x1a\n" +
	"\bmentions\x18\b \x03(\x03R\bmentions\x12\x1e\n" +
	"\n" +
	"visibility\x18\t \x01(\tR\n" +
	"visibility\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAtB\v\n" +
	"\t_reply_to\"1\n" +
	"\x16GetConversationRequest\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\"T\n" +
	"\x17GetConversationResponse\x129\n" +
	"\fconversation\x18\x01 \x01(\v2\x15.message.ConversationR\fconversation\"\xd4\x01\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.message.ConversationTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\x03R\aownerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x125\n" +
	"\amembers\x18\x06 \x03(\v2\x1b.message.ConversationMemberR\amembers\"\xb3\x01\n" +
	"\x12ConversationMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12-\n" +
	"\x04role\x18\x02 \x01(\x0e2\x19.message.ConversationRoleR\x04role\x12\x14\n" +
	"\x05muted\x18\x03 \x01(\bR\x05muted\x12\"\n" +
	"\rlast_read_seq\x18\x04 \x01(\x03R\vlastReadSeq\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\x03R\bjoinedAt\"\x9a\x01\n" +
	"\x19CreateConversationRequest\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.message.ConversationTypeR\x04type\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x04 \x03(\x03R\tmemberIds\"O\n" +
	"\x1aCreateConversationResponse\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Z\n" +
	"\x14UpdateReadSeqRequest\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\"1\n" +
	"\x15UpdateReadSeqResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9d\x01\n" +
	"\x17NotifyNewMessageRequest\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\tR\x05msgId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\x03R\bsenderId\x12#\n" +
	"\rrecipient_ids\x18\x05 \x03(\x03R\frecipientIds\"[\n" +
	"\x18NotifyNewMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0enotified_count\x18\x02 \x01(\x05R\rnotifiedCount*6\n" +
	"\x10ConversationType\x12\n" +
	"\n" +
	"\x06DIRECT\x10\x00\x12\t\n" +
	"\x05GROUP\x10\x01\x12\v\n" +
	"\aCHANNEL\x10\x02*O\n" +
	"\x10ConversationRole\x12\t\n" +
	"\x05OWNER\x10\x00\x12\t\n" +
	"\x05ADMIN\x10\x01\x12\r\n" +
	"\tPUBLISHER\x10\x02\x12\n" +
	"\n" +
	"\x06MEMBER\x10\x03\x12\n" +
	"\n" +
	"\x06VIEWER\x10\x042\x85\x04\n" +
	"\x0eMessageService\x12H\n" +
	"\vSendMessage\x12\x1b.message.SendMessageRequest\x1a\x1c.message.SendMessageResponse\x12K\n" +
	"\fPullMessages\x12\x1c.message.PullMessagesRequest\x1a\x1d.message.PullMessagesResponse\x12T\n" +
	"\x0fGetConversation\x12\x1f.message.GetConversationRequest\x1a .message.GetConversationResponse\x12]\n" +
	"\x12CreateConversation\x12\".message.CreateConversationRequest\x1a#.message.CreateConversationResponse\x12N\n" +
	"\rUpdateReadSeq\x12\x1d.message.UpdateReadSeqRequest\x1a\x1e.message.UpdateReadSeqResponse\x12W\n" +
	"\x10NotifyNewMessage\x12 .message.NotifyNewMessageRequest\x1a!.message.NotifyNewMessageResponseB?Z=github.com/yourusername/im-system/api/proto/message;messagepbb\x06proto3"

var (
	file_message_message_proto_rawDescOnce sync.Once
	file_message_message_proto_rawDescData []byte
)

func file_message_message_proto_rawDescGZIP() []byte {
	file_message_message_proto_rawDescOnce.Do(func() {
		file_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_message_proto_rawDesc), len(file_message_message_proto_rawDesc)))
	})
	return file_message_message_proto_rawDescData
}

var file_message_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_message_message_proto_goTypes = []any{
	(ConversationType)(0),              // 0: message.ConversationType
	(ConversationRole)(0),              // 1: message.ConversationRole
	(*SendMessageRequest)(nil),         // 2: message.SendMessageRequest
	(*SendMessageResponse)(nil),        // 3: message.SendMessageResponse
	(*PullMessagesRequest)(nil),        // 4: message.PullMessagesRequest
	(*PullMessagesResponse)(nil),       // 5: message.PullMessagesResponse
	(*Message)(nil),                    // 6: message.Message
	(*GetConversationRequest)(nil),     // 7: message.GetConversationRequest
	(*GetConversationResponse)(nil),    // 8: message.GetConversationResponse
	(*Conversation)(nil),               // 9: message.Conversation
	(*ConversationMember)(nil),         // 10: message.ConversationMember
	(*CreateConversationRequest)(nil),  // 11: message.CreateConversationRequest
	(*CreateConversationResponse)(nil), // 12: message.CreateConversationResponse
	(*UpdateReadSeqRequest)(nil),       // 13: message.UpdateReadSeqRequest
	(*UpdateReadSeqResponse)(nil),      // 14: message.UpdateReadSeqResponse
	(*NotifyNewMessageRequest)(nil),    // 15: message.NotifyNewMessageRequest
	(*NotifyNewMessageResponse)(nil),   // 16: message.NotifyNewMessageResponse
	(*structpb.Struct)(nil),            // 17: google.protobuf.Struct
}
var file_message_message_proto_depIdxs = []int32{
	0,  // 0: message.SendMessageRequest.conv_type:type_name -> message.ConversationType
	17, // 1: message.SendMessageRequest.body:type_name -> google.protobuf.Struct
	6,  // 2: message.PullMessagesResponse.messages:type_name -> message.Message
	0,  // 3: message.Message.conv_type:type_name -> message.ConversationType
	17, // 4: message.Message.body:type_name -> google.protobuf.Struct
	9,  // 5: message.GetConversationResponse.conversation:type_name -> message.Conversation
	0,  // 6: message.Conversation.type:type_name -> message.ConversationType
	10, // 7: message.Conversation.members:type_name -> message.ConversationMember
	1,  // 8: message.ConversationMember.role:type_name -> message.ConversationRole
	0,  // 9: message.CreateConversationRequest.type:type_name -> message.ConversationType
	2,  // 10: message.MessageService.SendMessage:input_type -> message.SendMessageRequest
	4,  // 11: message.MessageService.PullMessages:input_type -> message.PullMessagesRequest
	7,  // 12: message.MessageService.GetConversation:input_type -> message.GetConversationRequest
	11, // 13: message.MessageService.CreateConversation:input_type -> message.CreateConversationRequest
	13, // 14: message.MessageService.UpdateReadSeq:input_type -> message.UpdateReadSeqRequest
	15, // 15: message.MessageService.NotifyNewMessage:input_type -> message.NotifyNewMessageRequest
	3,  // 16: message.MessageService.SendMessage:output_type -> message.SendMessageResponse
	5,  // 17: message.MessageService.PullMessages:output_type -> message.PullMessagesResponse
	8,  // 18: message.MessageService.GetConversation:output_type -> message.GetConversationResponse
	12, // 19: message.MessageService.CreateConversation:output_type -> message.CreateConversationResponse
	14, // 20: message.MessageService.UpdateReadSeq:output_type -> message.UpdateReadSeqResponse
	16, // 21: message.MessageService.NotifyNewMessage:output_type -> message.NotifyNewMessageResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_message_message_proto_init() }
func file_message_message_proto_init() {
	if File_message_message_proto != nil {
		return
	}
	file_message_message_proto_msgTypes[0].OneofWrappers = []any{}
	file_message_message_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_message_proto_rawDesc), len(file_message_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_message_proto_goTypes,
		DependencyIndexes: file_message_message_proto_depIdxs,
		EnumInfos:         file_message_message_proto_enumTypes,
		MessageInfos:      file_message_message_proto_msgTypes,
	}.Build()
	File_message_message_proto = out.File
	file_message_message_proto_goTypes = nil
	file_message_message_proto_depIdxs = nil
}
