server:
  gateway:
    grpc_port: 50051
  router:
    grpc_port: 50052
  message:
    grpc_port: 50053
  user:
    grpc_port: 50054
  file:
    http_port: 8080
    mode: debug
    max_file_size: 524288000  # 500MB in bytes

consul:
  address: localhost:8500
  scheme: http
  datacenter: dc1
  health_check_interval: 10s
  deregister_after: 30s

database:
  host: localhost
  port: 5432
  user: imuser
  password: impassword
  dbname: im_system
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool_size: 10

jwt:
  secret: your-secret-key-change-in-production
  expiry: 24h

s3:
  endpoint: ""
  region: us-east-1
  bucket: im-files
  access_key: ""
  secret_key: ""
  use_ssl: true

log:
  level: info
  encoding: json
  output_paths:
    - stdout
    - logs/app.log

message:
  retention_days: 30
  max_pull_limit: 100

file:
  max_size_mb: 500
  allowed_types:
    - image/jpeg
    - image/png
    - image/gif
    - video/mp4
    - audio/mpeg
    - application/pdf
